---
- name: Install cron and curl
  apt:
    name:
      - cron
      - curl
    state: present

- name: Enable cron service
  service:
    name: cron
    state: started
    enabled: yes

- name: Install Duck DNS cron job for domain {{ duckdns_domain }}
  cron:
    name: duckdns
    user: "{{ duckdns_cronjob_user }}"
    day: "*"
    hour: "*"
    minute: "*/5"
    job: curl -k -o {{ duckdns_log_file }} "https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip="
    state: present
