---
services:
  vaultwarden: 
    subdomain: passwords
    port: 8080

  syncthing: 
    subdomain: syncthing
    port: 8384

  transmission: 
    subdomain: transmission
    port: 9091

  navidrome: 
    subdomain: music
    port: 4533

  ntfy:
    subdomain: ntfy
    port: 6666
